#!/bin/bash

cd src

tsc general.ts SVGelement.ts \
    List_Item/List_Item.ts \
    List_Item/Electro_Item.ts \
    List_Item/*.ts \
    Properties.ts SVGSymbols.ts Hierarchical_List.ts Print_Table.ts config.ts ../prop/prop_scripts.ts main.ts --outfile swap.js 

cat GPL3.js swap.js > eendraadschema.js
cp eendraadschema.js ..
rm swap.js

cd ..

echo "var CONF_builddate=\""`date +%Y%m%d-%H%M%S`"\"" > builddate.js
