export const changelog = [
  { date: "2025-09-18", msg: "Eerste stapjes om symbolen toe te voegen aan het situatieschema die niet in het ééndraadschema zitten." },
  { date: "2025-08-22", msg: "Aftakdoos kan nu meerdere kinderen bevatten." },
  { date: "2025-08-19", msg: "Kring en Aansluiting kennen nu ook de bescherming \"zekeringscheider\"." },
  { date: "2025-07-29", msg: "Bij handmatig pagineren kan voor iedere pagina van het ééndraadschema een andere info-tekst gekozen worden om rechts onder te tonen bij het afprinten." },
  { date: "2025-07-28", msg: "Voor elementen op het hoogste niveau kan gekozen worden om tijdens het printen altijd een nieuwe pagina te starten." },
  { date: "2025-07-20", msg: "Micro-omvormer optie toegevoegd. Voor omvormers met maximaal één aansluiting kan nu \"micro\" worden aangevinkt, wat resulteert in een dunnere lijndikte in het schema." },
  { date: "2025-07-20", msg: "Mogelijkheid om slechts bepaalde pagina's af te drukken uit het schema." },
  { date: "2025-07-07", msg: "Symbool voor afzuigkap (in Ventilator) en aarding (in Zeldzame symbolen)." },
  { date: "2025-07-05", msg: "Verbeteringen en meer mogelijkheden aan het contact/contactor symbool (binnen Kring, of Schakelaars)." },
  { date: "2025-07-01", msg: "Automatische nummering en automatische naamgeving voor kringen." },
  { date: "2025-06-26", msg: "De elecktriciteitsmeter van een aansluiting kan nu ook in het situatieschema worden toegevoegd." },
  { date: "2025-06-24", msg: "Mogelijkheid om files op te slaan zonder compressie." },
  { date: "2025-06-21", msg: "Wijzigingen aan het symbool voor \"Omvormer\". Zowel zonnepanelen als een batterij kunnen nu aan dezelfde omvormer worden gehangen." },
  { date: "2025-06-08", msg: "De externe sturing van een domotica gestuurde verbruiker kan nu ook op het situatieplan worden toegevoegd (schakelaar/drukkknop)." },
  { date: "2025-05-25", msg: "Omvormer kan nu ook \"in kring\" worden geplaatst indien deze als backup kan dienen." },
  { date: "2025-05-19", msg: "Support om meerdere elementen in het situatieschema tegelijkertijd te selecteren (met shift-click) en tegelijkertijd te bewerken." },
  { date: "2025-05-01", msg: "Automatisch opslaan van schema's in de browsercache (crash of ongewenste browser refresh recovery)." },
  { date: "2025-04-06", msg: "Bij kringen kan nu ook de fase worden ingesteld (Fase 1, Fase 2, Fase 3)." },
  { date: "2025-03-01", msg: "Inbouwen functionaliteit om meerdere eendraadschema's samen te voegen op het \"Bestand\"-scherm." },
  { date: "2025-03-01", msg: "Mogelijkheid tot vergrendelen van symbolen in het situatieschema (Ctrl L)." },
  { date: "2025-02-28", msg: "Borden kunnen nu ook worden toegevoegd aan het situatieschema." },
  { date: "2025-02-16", msg: "Toevoegen sidebar in het situatieschema om makkelijker symbooltjes toe te voegen." }
];